edward = User.create!(email: "edward@lewagon.com", password: "azertyuiop", first_name: "Edward", avatar_url: "http://graph.facebook.com/10152948868146275/picture")
boris = User.create!(email: "boris@lewagon.com", password: "azertyuiop", first_name: "Boris", avatar_url: "https://avatars.githubusercontent.com/u/2471555?v=3")
seb = User.create!(email: "seb@lewagon.com", password: "azertyuiop", first_name: "Seb", avatar_url: "https://avatars.githubusercontent.com/u/414418?v=3")
romain = User.create!(email: "romain@lewagon.com", password: "azertyuiop", first_name: "Romain", avatar_url: "https://avatars.githubusercontent.com/u/6377103?v=3")

c1 = Conversation.create!(user1: edward, user2: boris)
c2 = Conversation.create!(user1: edward, user2: seb)
c3 = Conversation.create!(user1: edward, user2: romain)
c4 = Conversation.create!(user1: boris, user2: seb)
c5 = Conversation.create!(user1: boris, user2: romain)
c6 = Conversation.create!(user1: seb, user2: romain)

m1 = Message.create!(user: edward, conversation: c1, content: "Hey")
m2 = Message.create!(user: edward, conversation: c2, content: "Hello")
m3 = Message.create!(user: edward, conversation: c3, content: "What's up?")
m4 = Message.create!(user: boris, conversation: c1, content: "Salut Edward")
m5 = Message.create!(user: seb, conversation: c2, content: "Yo!")
m6 = Message.create!(user: romain, conversation: c3, content: "Tu peux pas test")
m7 = Message.create!(user: boris, conversation: c4, content: "Salut Seb")
m8 = Message.create!(user: boris, conversation: c5, content: "Salut Romain")
m9 = Message.create!(user: seb, conversation: c6, content: "Hey!")
m10 = Message.create!(user: seb, conversation: c4, content: "Hello")
m11 = Message.create!(user: romain, conversation: c5, content: "Quoi de neuf ?")
m12 = Message.create!(user: romain, conversation: c6, content: "Tu fais quoi demain ?")